# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 418254bc4fa5f0fd138b85537df9b6c816ff4e8913b052832bb0c4836ea892472ec956ae4300c742db4afb5a4bb50a7396a1657094e6f414eabeea9faf13d6bd
  mail_admin: no-reply@miele.cl
  mailer_user: no-reply@miele.cl
  mailer_password: BFgUQc8owQfjbVnfcOhU0bM9Qi+YQbw2ak3hb5iOkbM9
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w
  webpay_wsdl: https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_develop.crt
  webpay_client_private_key: config/private_key_develop.key
  webpay_tbk_certificate: config/tbk_develop.key
  webpay_commerce_code: "597020000540"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "INTEGRACION"
  webpay_logger: "webpay_development.log"
  mercadopago_client_id: <%= ENV["MERCADOPAGO_CLIENT_ID"] %>
  mercadopago_client_secret: <%= ENV["MERCADOPAGO_CLIENT_SECRET"] %>
  #### link a la mesa de ayuda en service desk de jira, reemplazar por el correspondiente, pedir a naty
  service_desk: https://oferus.atlassian.net/servicedesk/customer/portal/36
  #### token del chat de fb, pedir a martin
  chatbot_token: 434752596964558
  public_key_captcha: "6Lct5fUUAAAAAGB4bx_jIPRWBEwaXGOJelR-VGy7"
  private_key_captcha: "6Lct5fUUAAAAAC8tkltcvREzcspio5v7wyofEZiG"
  contact_mails: ["onlineshop@miele.cl"]
  aws:
    s3_credentials:
      access_key_id: AKIAWX4TLH64GHGZLMQU
      secret_access_key: 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
      bucket: mieleb2c-cl
  webpay:
    key_id: "597055555532"
    key_secret: "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
  miele_b2b_api:
    email: "ecommercemiele@garagelabs.cl"
    token: gpNUfQMH89WwLIylitXd4Qtt
    url_base: "http://preprod.miele.garagelabs.cl"
  ############################################
  # APUNTA A STAGING PARA LAS MASIVAS DE QA
  miele_tickets_api:
    token: kdOQrQZ1tQr2C0DXBYj3kAtt
    url_base: https://mieletickets.garagelabs.cl
    #token: uTVCZJjRxIJYkz9FaS50Rgtt # credencial de pre produccion
    #url_base: https://preprod.mieletickets.garagelabs.cl # credencial de preproduccion
  ############################################
  # APUNTA A STAGING PARA LAS MASIVAS DE QA
  miele_core_api:
    token: wbBsf6O6fpJBvFschcsvUAtt
    url_base: https://mielecore.garagelabs.cl

test:
  secret_key_base: de7ac37ab1c9fedf573d745093653ccf5405f51c6911a365e55dc7eb01dd82892826d7009a62bc11cbd89f9b96b3b70c7de32fc8f077b5efc6c86f875c78e14a
  webpay_wsdl: https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_develop.crt
  webpay_client_private_key: config/private_key_develop.key
  webpay_tbk_certificate: config/tbk_develop.key
  webpay_commerce_code: "597020000540"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "CERTIFICACION"
  webpay_logger: "webpay_development.log"
  mercadopago_client_id: <%= ENV["MERCADOPAGO_CLIENT_ID"] %>
  mercadopago_client_secret: <%= ENV["MERCADOPAGO_CLIENT_SECRET"] %>
  #### link a la mesa de ayuda en service desk de jira, reemplazar por el correspondiente, pedir a naty
  service_desk: https://oferus.atlassian.net/
  #### token del chat de fb, pedir a martin
  chatbot_token: 434752596964558
  public_key_captcha: "6Lct5fUUAAAAAGB4bx_jIPRWBEwaXGOJelR-VGy7"
  private_key_captcha: "6Lct5fUUAAAAAC8tkltcvREzcspio5v7wyofEZiG"
  contact_mails: ["onlineshop@miele.cl"]
  aws:
    s3_credentials:
      access_key_id: "AKIAWX4TLH64GHGZLMQU"
      secret_access_key: "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"
      bucket: "mieleb2c-cl"
  webpay:
    key_id: "597055555532"
    key_secret: "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: 98c8fdd5f790115a714a6194a0f90be47edd9e9badbc016c5cc1fda0db35c59d05c1c36ee687b6dc0f954bed87baf56f37191d59ecac8b2e41db783a8bee9085
  mail_admin: no-reply@miele.cl
  mailer_user: no-reply@miele.cl
  mailer_password: BFgUQc8owQfjbVnfcOhU0bM9Qi+YQbw2ak3hb5iOkbM9
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w
  miele_mailer_user: Ext-CL-*
  miele_mailer_pass: 11lIEwZVHaiBAaP3h4MS78NuLQxY
  webpay_wsdl: https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_develop.crt
  webpay_client_private_key: config/private_key_develop.key
  webpay_tbk_certificate: config/tbk_develop.key
  webpay_commerce_code: "597020000540"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "INTEGRACION"
  webpay_logger: "webpay_development.log"
  mercadopago_client_id: <%= ENV["MERCADOPAGO_CLIENT_ID"] %>
  mercadopago_client_secret: <%= ENV["MERCADOPAGO_CLIENT_SECRET"] %>
  #### link a la mesa de ayuda en service desk de jira, reemplazar por el correspondiente, pedir a naty
  service_desk: https://oferus.atlassian.net/servicedesk/customer/portal/36
  #### token del chat de fb, pedir a martin
  chatbot_token: 434752596964558
  #### link de google tag manager, pedir a martin
  tag_manager_token: GTM-W98DDWX
  public_key_captcha: "6Lct5fUUAAAAAGB4bx_jIPRWBEwaXGOJelR-VGy7"
  private_key_captcha: "6Lct5fUUAAAAAC8tkltcvREzcspio5v7wyofEZiG"
  contact_mails: ["onlineshop@miele.cl"]
  webpay:
    key_id: "597055555532"
    key_secret: "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
  ############################################
  # APUNTA A PRE-PRODUCCION
  miele_b2b_api:
    email: "ecommercemiele@garagelabs.cl"
    token: gpNUfQMH89WwLIylitXd4Qtt
    url_base: "http://preprod.miele.garagelabs.cl"
  ############################################
  # APUNTA A STAGING PARA LAS MASIVAS DE QA
  miele_tickets_api:
    token: kdOQrQZ1tQr2C0DXBYj3kAtt
    url_base: https://mieletickets.garagelabs.cl
    #token: uTVCZJjRxIJYkz9FaS50Rgtt # credencial de pre produccion
    #url_base: https://preprod.mieletickets.garagelabs.cl # credencial de preproduccion
  ############################################
  # APUNTA A STAGING PARA LAS MASIVAS DE QA
  miele_core_api:
    token: wbBsf6O6fpJBvFschcsvUAtt
    url_base: https://mielecore.garagelabs.cl
    #token: ZYLTpLYB7oCSVCBFzIjueAtt # credencial de pre produccion
    #url_base: "https://preprod.mielecore.garagelabs.cl" # credencial de pre produccion
# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: 2b2d380e15b01cfed14cd4027b3cd22bedaf00ba2133c9b6a1dd828ef1a8a4205a8347f4e6594700f5acba9b1a56e3dfc4c9caf4a95ef4f969712da057760629
  mail_admin: no-reply@miele.cl
  mailer_user: no-reply@miele.cl
  mailer_password: BFgUQc8owQfjbVnfcOhU0bM9Qi+YQbw2ak3hb5iOkbM9
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w
  webpay_wsdl: https://webpay3g.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_production.crt
  webpay_client_private_key: config/private_key_production.key
  webpay_tbk_certificate: config/tbk_production.key
  webpay_commerce_code: "597035628479"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "PRODUCCION"
  webpay_logger: "webpay_production.log"
  mercadopago_client_id: <%= ENV["MERCADOPAGO_CLIENT_ID"] %>
  mercadopago_client_secret: <%= ENV["MERCADOPAGO_CLIENT_SECRET"] %>
  #### link a la mesa de ayuda en service desk de jira, reemplazar por el correspondiente, pedir a naty
  service_desk: https://oferus.atlassian.net/servicedesk/customer/portal/36
  #### token del chat de fb, pedir a martin
  chatbot_token: 434752596964558
  #### link de google tag manager, pedir a martin
  tag_manager_token: GTM-W98DDWX
  public_key_captcha: "6Lesm0gaAAAAAPqV1eW5Y1v1k6yt9IOdsF_cn7vk"
  private_key_captcha: "6Lesm0gaAAAAAEjWU_h6o0MsbX96QmJrLNHvyGUs"
  contact_mails: ["onlineshop@miele.cl", "josefina.escobar@miele.com"]
  aws:
    s3_credentials:
      access_key_id: "AKIAWX4TLH64GHGZLMQU"
      secret_access_key: "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"
      bucket: "mieleb2c-cl"
  webpay:
    key_id: "597035628479"
    key_secret: "b73ddbb4047c1dfb29244e42324229df"
  miele_b2b_api:
    email: "ecommercemiele@garagelabs.cl"
    token: JfHcnEVuKZvjMqHekPYG
    url_base: "https://www.mielecustomers.cl/"
  miele_tickets_api:
    token: uTVCZJjRxIJYkz9FaS50Rgtt
  url_base: https://tickets.mielecustomers.cl
  miele_core_api:
    token: quard7eXXnXllrJ7QQsZbwtt
    url_base: https://core.mielecustomers.cl
